name: "Agregar enlace"
description: "Crear o actualizar un enlace corto"
title: "[LINK]"
body:
  - type: textarea
    id: data
    attributes:
      label: Datos
      description: "Escribe en este formato:"
      value: |
        slug=mi-app
        url=https://...
    validations:
      required: true
